[project]
name = "cr_enhanced_report"
version = "0.0.3"
description = "Enhanced report for Cosmic-Ray."
keywords = [
    "cosmic-ray",
    "enhanced report",
    "mutation",
    "plugin",
    "testing",
]
authors = [
    {name="Peter McDonald", email="git@petermcdonald.co.uk"}
]
maintainers = [
    {name="Peter McDonald", email="git@petermcdonald.co.uk"}
]
readme = {file="README.md", content-type="text/markdown"}
license = "MIT"
requires-python = "<3.14,>=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Bug Tracking",
    "Topic :: Software Development :: Testing",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "cosmic-ray>=8.7"
]

[project.urls]
Homepage = "https://github.com/petermcd/cr_enhanced_report"
Documentation = "https://github.com/petermcd/cr_enhanced_report"
Repository = "https://github.com/petermcd/cr_enhanced_report"
Issues = "https://github.com/petermcd/cr_enhanced_report/issues"

[build-system]
requires = ["setuptools>=84", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pygments>=2.21.0", # Minimum version to resolve security issue
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
]

[project.scripts]
cr-enhanced-report = "cr_enhanced_report:cli.main"

[tool.pytest.ini_options]
addopts = "--cov=cr_enhanced_report --cov-report term-missing --cov-report xml:coverage.xml"

[tool.ruff]
line-length = 120

[cosmic-ray]
module-path = "cr_enhanced_report"
timeout = 10.0
excluded-modules = []
test-command = "uv run pytest"

[cosmic-ray.distributor]
name = "local"
